networks:
 default:
    name: ${docker_network}
    external: true

services:
  # REST<=>MCP gateway
  mcp-gateway:
    image: itaru2622/mcp:bookworm
    ports:
      - 8888:8888
      - 8889:8889
    environment:
      - FASTMCP_EXPERIMENTAL_ENABLE_NEW_OPENAPI_PARSER=true
      - wDir=${wDir}
      - sDir=${sDir}
      - PYTHONPATH=${sDir}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${wDir}:${wDir}
    working_dir: ${wDir}
    command: tail -f /bin/bash
    restart: always


  # MCP inspector
  inspector:
    image: node:22-bookworm
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - DANGEROUSLY_OMIT_AUTH=true
      - CLIENT_PORT=3000
      - SERVER_PORT=3001
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    command: npx @modelcontextprotocol/inspector
    restart: always

# swagger editor supporting openAPI v3.1 and try-it-out
  swagger:
    image: docker.swagger.io/swaggerapi/swagger-editor:next-v5
    ports:
      - 8080:80
    environment:
      - wDir=${wDir}
      - sDir=${sDir}
#     - REACT_APP_SWAGEER_FILE=my/ghec-get.json
    volumes:
      - ${wDir}:${wDir}
    restart: always
