networks:
 default:
    name: ${docker_network}
    external: true

services:
  # REST<=>MCP gateway
  mcp-gateway:
    image: itaru2622/mcp:trixie
    ports:
      - ${port_mcpgateway}:${port_mcpgateway}
    privileged: true
    environment:
      - FASTMCP_EXPERIMENTAL_ENABLE_NEW_OPENAPI_PARSER=true
      - wDir=${wDir}
      - sDir=${sDir}
      - myIP=${myIP}
      - GH_MCP_PAT=${GH_MCP_PAT}
      - PYTHONPATH=${sDir}
    volumes:
      - ${wDir}:${wDir}
      - /etc/resolv.conf:/etc/resolv.conf:ro
    working_dir: ${wDir}
    restart: always


  # MCP inspector
  inspector:
    image: node:22-trixie
    ports:
      - ${port_inspector}:${port_inspector}
      - ${port_inspector_proxy}:${port_inspector_proxy}
    environment:
      - DANGEROUSLY_OMIT_AUTH=true
      - CLIENT_PORT=${port_inspector}
      - SERVER_PORT=${port_inspector_proxy}
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    command: npx @modelcontextprotocol/inspector
    restart: always

# swagger editor supporting openAPI v3.1 and try-it-out
  swagger:
    image: docker.swagger.io/swaggerapi/swagger-editor:next-v5
    ports:
      - ${port_swagger}:80
    environment:
      - wDir=${wDir}
      - sDir=${sDir}
#     - REACT_APP_SWAGEER_FILE=my/ghec-get.json
    volumes:
      - ${wDir}:${wDir}
    restart: always
